name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # a cada hora (UTC)
  workflow_dispatch: # adiciona o botão de execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Action pré-existente: Faz checkout do código-fonte
      - name: Checkout do código
        uses: actions/checkout@v3

      # Action pré-existente: Instala o .NET SDK
      - name: Instala o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # ou a versão que estiver usando

      # Script personalizado: Roda o build do projeto
      - name: Compila o projeto
        run: dotnet build

      # Script personalizado: Roda os testes (se houver)
      - name: Executa testes
        run: dotnet test
