name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore github-actions-dotnet-webapp.sln

      - name: Compilar a solução
        run: dotnet build github-actions-dotnet-webapp.sln --no-restore

      - name: Executar testes
        run: dotnet test github-actions-dotnet-webapp.sln --no-build

