name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # A cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore MeuApp/MeuApp.csproj

      - name: Compilar o projeto
        run: dotnet build MeuApp/MeuApp.csproj --no-restore

      - name: Rodar testes
        run: dotnet test MeuApp/MeuApp.csproj --no-build


